apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-java
  namespace: devsu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops-java
  template:
    metadata:
      labels:
        app: demo-devops-java
    spec:
      containers:
        - name: app
          image: bsaulestradah/demo-devops-java:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: demo-config
            - secretRef:
                name: demo-secret
