apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: devsu
spec:
  type: NodePort
  selector:
    app: demo-devops-java
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
